### ISSUE TITLE
Potentially incorrect documentation?

### ISSUE THREAD

**Issue by f00d4tehg0dz** [justinjk007/thaNAS#1]
You have listed in the documentation --vault-pass-file
```
ansible-playbook setup_thaNAS_playbook.yml -i ansible_hosts.conf --vault-pass-file ansible_vault_password.txt
ansible-playbook setup_thaNAS_playbook.yml -i ansible_hosts.conf --vault-pass-file ansible_vault_password.txt --tags transmission
```

However that gave me an error, I believe you meant to say --vault-password-file, as seen below.
```
ansible-playbook setup_thaNAS_playbook.yml -i ansible_hosts.conf --vault-password-file ansible_vault_password.txt
ansible-playbook setup_thaNAS_playbook.yml -i ansible_hosts.conf --vault-password-file ansible_vault_password.txt --tags transmission
```

**Comment by justinjk007** [comment]
What's the version of Ansible you're using? My snippets are correct, it works with whatever pip let's you install.

**Comment by f00d4tehg0dz** [comment]
Ah you're correct. I was originally using cygwin before running into other complications. Switched to Debian, and seems fine now! Thanks!
